# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('college', models.CharField(default='NA', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='StudMarks',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('sem_1', models.FloatField(blank=True, default=0)),
                ('sem_2', models.FloatField(blank=True, default=0)),
                ('sem_3', models.FloatField(blank=True, default=0)),
                ('sem_4', models.FloatField(blank=True, default=0)),
                ('sem_5', models.FloatField(blank=True, default=0)),
                ('sem_6', models.FloatField(blank=True, default=0)),
                ('sem_7', models.FloatField(blank=True, default=0)),
                ('sem_8', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
