# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0003_auto_20180106_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studmarks',
            name='usn',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
